[package]
name = "khaos_napi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
khaos_core = { path = "../khaos_core" }
napi = { version = "3.3.0", default-features = false, features = ["napi8"] }
napi-derive = "3.2.5"

[build-dependencies]
napi-build = "2.2.3"
